//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Membership_Registration_Update.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
        
    public partial class NewentryTB
    {
        public int Id { get; set; }
        public string Reference_No { get; set; }
        public string FullName { get; set; }
        [DataType(DataType.DateTime)]
        public System.DateTime Date_Printed { get; set; }
        public Nullable<System.DateTime> Date_Approved { get; set; }
        public string RegID { get; set; }
        public string Status { get; set; }
        public string Remark { get; set; }
    
        public virtual Regstatu Regstatu { get; set; }
    }
}
